name: python test

on:
  push:
    branches:
      - main
      - develop
      - 'fix/**'
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
      - name: Install dependencies
        run: |
          poetry export -f requirements.txt > requirements.txt
          pip install -r requirements.txt
      - name: Test with pytest
        run: python -m unittest discover tests -v
